/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  learning_sql: [{type: 'autogenerated', dirName: 'learning-sql'}],
  learning_sql_001: [{type: 'autogenerated', dirName: 'learning-sql-001'}],
  learning_sql2: [{type: 'autogenerated', dirName: 'learning-sql-002'}],
  learning_sql3: [{type: 'autogenerated', dirName: 'learning-sql-003'}],
  learning_sql4: [{type: 'autogenerated', dirName: 'learning-sql-004'}],
  learning_sql5: [{type: 'autogenerated', dirName: 'learning-sql-005'}],
  learning_sql6: [{type: 'autogenerated', dirName: 'learning-sql-006'}],
  learning_sql7: [{type: 'autogenerated', dirName: 'learning-sql-007'}],
  learning_sql8: [{type: 'autogenerated', dirName: 'learning-sql-008'}],
  learning_sql9: [{type: 'autogenerated', dirName: 'learning-sql-009'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};
