/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

const bookConfig = require('./readingbookConfig');

let sideBarConfig = {}
bookConfig.booksInfo.forEach((bookItem) => sideBarConfig[bookItem.bookDir] = [{type: 'autogenerated', dirName: bookItem.bookDir}])

module.exports = sideBarConfig;

// {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   wwdc: [{type: 'autogenerated', dirName: 'wwdc'}],
//   // But you can create a sidebar manually
//   /*
//   tutorialSidebar: [
//     {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['hello'],
//     },
//   ],
//    */
// };
